### ISSUE TITLE
Consider defining CSS vars in terms of SASS vars

### ISSUE THREAD

**Issue by michaellenaghan** [imperavi/superkube#17]
In the current approach, Superkube defines a CSS var:

```css
.nav {
    --nav-link-color: blue;
}
```

and users re-define that var:

```css
.nav {
    --nav-link-color: red;
}
```

Both definitions end up in the final CSS, making it a little bigger and a little more complicated than it otherwise might be.

Consider instead defining CSS vars in terms of SASS vars:

```css
$nav-link-color: blue !default;
.nav {
    --nav-link-color: #{$nav-link-color};
}
```
