### ISSUE TITLE
The link module only generates links for the default text scale

### ISSUE THREAD

**Issue by michaellenaghan** [imperavi/superkube#18]
The link module generates links for each [text scale](https://github.com/imperavi/superkube/blob/d87dcc75755b4d557b8a9601c657c4ab71a88f88/superkube/vars/scales.scss#L43) (`medium`, `large`, etc.) [here](https://github.com/imperavi/superkube/blob/427ed672d528ef316cb1aa74c610e8d2cf283025/superkube/modules/link.scss#L79). 

It doesn't currently generate variants for each responsive breakpoint (`sm`, `md`, `lg`).

Until they're added, here's one way to add them yourself:

```scss
@mixin generate-link-size($map, $breakpoint) {
    $obj: map-get($map, text);
    @each $key, $val in $obj {
        @if (type-of($val) == 'list') {
            &-#{$key} {
                font-size: #{type-size(text, $key, $breakpoint)};
            }
        }
    }
}

// .link { @include generate-link-size(scale(type), std); }
@include for-lg { .link { @include generate-link-size(scale(type-lg), lg); }}
@include for-md { .link { @include generate-link-size(scale(type-md), md); }}
@include for-sm { .link { @include generate-link-size(scale(type-sm), sm); }}
```

(The first line is commented out because that's the default scale that's already being generated.)
